/**
 * Default AI agents created automatically for every new tenant on registration.
 * Each slug must match an agent implementation in agents/ folder.
 */
export const DEFAULT_AGENTS = [
  {
    slug: 'sales',
    name: 'Agente de Ventas',
    description: 'Analiza tendencias de ventas, identifica oportunidades de crecimiento y optimiza el rendimiento comercial.',
    objective: 'Maximizar ingresos identificando oportunidades de venta cruzada y productos estrella.',
    icon: 'TrendingUp',
    autonomyLevel: 'recommend_only',
    aiProvider: 'deepseek',
    analysisFrequency: 'daily',
    status: 'pending_config',
  },
  {
    slug: 'inventory',
    name: 'Agente de Inventario',
    description: 'Monitorea niveles de stock, predice necesidades de reabastecimiento y detecta productos de bajo movimiento.',
    objective: 'Mantener niveles óptimos de inventario, evitando quiebres de stock y excesos.',
    icon: 'Package',
    autonomyLevel: 'recommend_only',
    aiProvider: 'deepseek',
    analysisFrequency: 'daily',
    status: 'pending_config',
  },
  {
    slug: 'customers',
    name: 'Agente de Clientes',
    description: 'Identifica clientes en riesgo de abandono, oportunidades de fidelización y segmentos de alto valor.',
    objective: 'Aumentar retención y valor de por vida del cliente.',
    icon: 'Users',
    autonomyLevel: 'recommend_only',
    aiProvider: 'deepseek',
    analysisFrequency: 'weekly',
    status: 'pending_config',
  },
  {
    slug: 'appointments',
    name: 'Agente de Citas',
    description: 'Optimiza la agenda, reduce cancelaciones y maximiza la ocupación de profesionales.',
    objective: 'Maximizar ocupación y minimizar cancelaciones y no-shows.',
    icon: 'Calendar',
    autonomyLevel: 'recommend_only',
    aiProvider: 'deepseek',
    analysisFrequency: 'daily',
    status: 'pending_config',
  },
  {
    slug: 'marketing',
    name: 'Agente de Marketing',
    description: 'Genera campañas personalizadas, identifica el mejor momento para comunicaciones y sugiere promociones.',
    objective: 'Crear campañas efectivas basadas en datos de clientes y tendencias.',
    icon: 'Megaphone',
    autonomyLevel: 'recommend_only',
    aiProvider: 'deepseek',
    analysisFrequency: 'weekly',
    status: 'pending_config',
  },
  {
    slug: 'financial',
    name: 'Agente Financiero',
    description: 'Analiza rentabilidad, controla gastos, detecta anomalías y proyecta flujo de caja.',
    objective: 'Mejorar márgenes y detectar fugas de dinero.',
    icon: 'DollarSign',
    autonomyLevel: 'recommend_only',
    aiProvider: 'deepseek',
    analysisFrequency: 'weekly',
    status: 'pending_config',
  },
  {
    slug: 'suppliers',
    name: 'Agente de Proveedores',
    description: 'Optimiza compras, evalúa proveedores y detecta oportunidades de ahorro en insumos.',
    objective: 'Optimizar cadena de suministro y negociar mejores condiciones.',
    icon: 'Truck',
    autonomyLevel: 'recommend_only',
    aiProvider: 'deepseek',
    analysisFrequency: 'weekly',
    status: 'pending_config',
  },
  {
    slug: 'catalog',
    name: 'Agente de Catálogo',
    description: 'Optimiza precios, identifica productos estrella y sugiere mejoras al catálogo de servicios.',
    objective: 'Destacar productos rentables y mejorar la experiencia de navegación.',
    icon: 'BookOpen',
    autonomyLevel: 'recommend_only',
    aiProvider: 'deepseek',
    analysisFrequency: 'weekly',
    status: 'pending_config',
  },
] as const;

export const DEFAULT_EXPENSE_CATEGORIES = [
  'Alquiler',
  'Sueldos y honorarios',
  'Productos e insumos',
  'Servicios (agua, luz, internet)',
  'Marketing y publicidad',
  'Mantenimiento y reparaciones',
  'Equipos y mobiliario',
  'Otros',
];
