/**
 * Default AI agents created automatically for every new tenant on registration.
 * Each slug must match an agent implementation in agents/ folder.
 */
export const DEFAULT_AGENTS = [
  {
    slug: 'sales',
    name: 'Agente de Ventas',
    description: 'Analiza tendencias de ventas, identifica oportunidades de crecimiento y optimiza el rendimiento comercial.',
    icon: 'TrendingUp',
    category: 'sales',
    autonomyLevel: 'recommend_only',
    aiProvider: 'deepseek',
    schedule: '0 8 * * *',
    isActive: false,
    status: 'pending_config',
  },
  {
    slug: 'inventory',
    name: 'Agente de Inventario',
    description: 'Monitorea niveles de stock, predice necesidades de reabastecimiento y detecta productos de bajo movimiento.',
    icon: 'Package',
    category: 'inventory',
    autonomyLevel: 'recommend_only',
    aiProvider: 'deepseek',
    schedule: '0 9 * * *',
    isActive: false,
    status: 'pending_config',
  },
  {
    slug: 'customers',
    name: 'Agente de Clientes',
    description: 'Identifica clientes en riesgo de abandono, oportunidades de fidelización y segmentos de alto valor.',
    icon: 'Users',
    category: 'customers',
    autonomyLevel: 'recommend_only',
    aiProvider: 'deepseek',
    schedule: '0 10 * * 1',
    isActive: false,
    status: 'pending_config',
  },
  {
    slug: 'appointments',
    name: 'Agente de Citas',
    description: 'Optimiza la agenda, reduce cancelaciones y maximiza la ocupación de profesionales.',
    icon: 'Calendar',
    category: 'appointments',
    autonomyLevel: 'recommend_only',
    aiProvider: 'deepseek',
    schedule: '0 7 * * *',
    isActive: false,
    status: 'pending_config',
  },
  {
    slug: 'marketing',
    name: 'Agente de Marketing',
    description: 'Genera campañas personalizadas, identifica el mejor momento para comunicaciones y sugiere promociones.',
    icon: 'Megaphone',
    category: 'marketing',
    autonomyLevel: 'recommend_only',
    aiProvider: 'deepseek',
    schedule: '0 11 * * 1',
    isActive: false,
    status: 'pending_config',
  },
  {
    slug: 'financial',
    name: 'Agente Financiero',
    description: 'Analiza rentabilidad, controla gastos, detecta anomalías y proyecta flujo de caja.',
    icon: 'DollarSign',
    category: 'financial',
    autonomyLevel: 'recommend_only',
    aiProvider: 'deepseek',
    schedule: '0 8 * * 1',
    isActive: false,
    status: 'pending_config',
  },
  {
    slug: 'suppliers',
    name: 'Agente de Proveedores',
    description: 'Optimiza compras, evalúa proveedores y detecta oportunidades de ahorro en insumos.',
    icon: 'Truck',
    category: 'suppliers',
    autonomyLevel: 'recommend_only',
    aiProvider: 'deepseek',
    schedule: '0 9 * * 2',
    isActive: false,
    status: 'pending_config',
  },
  {
    slug: 'catalog',
    name: 'Agente de Catálogo',
    description: 'Optimiza precios, identifica productos estrella y sugiere mejoras al catálogo de servicios.',
    icon: 'BookOpen',
    category: 'catalog',
    autonomyLevel: 'recommend_only',
    aiProvider: 'deepseek',
    schedule: '0 10 * * 3',
    isActive: false,
    status: 'pending_config',
  },
] as const;

export const DEFAULT_EXPENSE_CATEGORIES = [
  'Alquiler',
  'Sueldos y honorarios',
  'Productos e insumos',
  'Servicios (agua, luz, internet)',
  'Marketing y publicidad',
  'Mantenimiento y reparaciones',
  'Equipos y mobiliario',
  'Otros',
];
